### ISSUE TITLE
autorestart feature

### ISSUE THREAD

**Issue by TOWUK** [encode42/flags.sh#27]
add this please for windows, i dont wanted press CTRL + C spamming
![image](https://github.com/encode42/flags.sh/assets/28830162/de4a7fe3-6435-479b-9e19-56952b4056df)

**Comment by encode42** [comment]
Duplicate of #3

To add to this, you're always free to modify the generated script! Some users want their server to restart ASAP, some would like some time to kill it. Since it's such a simple modification to add a timeout (a single line), which isn't in high demand, a toggle on the frontend wouldn't serve much purpose.

**Comment by encode42** [comment]
However, the feature is extremely easy to implement on the frontend and backend, so I may add a toggle in the future.

**Comment by TOWUK** [comment]
> However, the feature is extremely easy to implement on the frontend and backend, so I may add a toggle in the future.

thanks!
