### ISSUE TITLE
[suggestion] Toggle for jdk.incubator.vector

### ISSUE THREAD

**Issue by mrfloris** [encode42/flags.sh#4]
Today I've learned that Paper doesn't use the API that enabled this, so it's not needed. That this is basically for Pufferfish and some other forks. 

Could there perhaps be a toggle or selection for type of server engine, so `--add-modules=jdk.incubator.vector` is optional, or when they select Pufferfish, etc. that it includes it (so when we pick Paper it doesn't)?

Just a small suggestion for a tweak.

**Comment by emielderckx** [comment]
This issue provides some useful information (mainly the last comment by Kevin) https://github.com/pufferfish-gg/Pufferfish/issues/46

**Comment by encode42** [comment]
Already added in the v2 rewrite

**Comment by encode42** [comment]
This issue was forgotten about! The site already has this toggle, albeit unintuitively.
![image](https://github.com/user-attachments/assets/3d68a140-d726-4fbf-98fd-544ea5cc8cd8)
It can be toggled via the very small and inconspicuous wrench icon next to "Flags". This will be improved in future iterations of the site.
